"""Initial migration

Revision ID: 14d626cc9eb3
Revises: 
Create Date: 2025-05-13 14:25:50.375032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d626cc9eb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('yt_url', sa.String(), nullable=False),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_index', sa.Integer(), nullable=False),
    sa.Column('fingerprint_hash', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_fingerprints')
    op.drop_table('songs')
    # ### end Alembic commands ###
