"""Initial Setup

Revision ID: 9e430f15a9d3
Revises:
Create Date: 2025-12-04 23:19:23.431744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e430f15a9d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("yt_url", sa.String(), nullable=False),
        sa.Column("thumbnail", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yt_url"),
    )
    op.create_table(
        "song_fingerprints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint_index", sa.Integer(), nullable=False),
        sa.Column("fingerprint_hash", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_song_fingerprints_fingerprint_hash"),
        "song_fingerprints",
        ["fingerprint_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_fingerprints_fingerprint_index"),
        "song_fingerprints",
        ["fingerprint_index"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_song_fingerprints_fingerprint_index"), table_name="song_fingerprints"
    )
    op.drop_index(
        op.f("ix_song_fingerprints_fingerprint_hash"), table_name="song_fingerprints"
    )
    op.drop_table("song_fingerprints")
    op.drop_table("songs")
    # ### end Alembic commands ###
