"""Added thumbnail to Songs

Revision ID: c5fc9e653fb5
Revises: e9997e99a177
Create Date: 2025-06-07 02:05:35.815620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fc9e653fb5'
down_revision: Union[str, None] = 'e9997e99a177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('thumbnail', sa.String(), nullable=False))
    op.drop_column('songs', 'album')
    op.create_unique_constraint('uq_song_yt_url', 'songs', ['yt_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('album', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('songs', 'thumbnail')
    op.drop_constraint('uq_song_yt_url', 'songs')
    # ### end Alembic commands ###
