"""Added indexing in hashes for faster lookup

Revision ID: e9997e99a177
Revises: 14d626cc9eb3
Create Date: 2025-05-15 15:11:37.922662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9997e99a177'
down_revision: Union[str, None] = '14d626cc9eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_song_fingerprints_fingerprint_hash'), 'song_fingerprints', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_song_fingerprints_fingerprint_index'), 'song_fingerprints', ['fingerprint_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_fingerprints_fingerprint_index'), table_name='song_fingerprints')
    op.drop_index(op.f('ix_song_fingerprints_fingerprint_hash'), table_name='song_fingerprints')
    # ### end Alembic commands ###
